export const emailTemplates = [
  { id: "announcement", label: "Announcement", description: "Studio news and new releases", subject: "Something new at ZCraft Studios", title: "A new chapter for your server.", content: "We have something new to share with you.\n\nAdd your announcement here, explain what is changing, and tell your community what to expect.", action: "Explore the studio", path: "/news", badge: "STUDIO UPDATE", color: "#73cec5" },
  { id: "maintenance", label: "Maintenance", description: "Planned downtime and service updates", subject: "Scheduled maintenance — ZCraft Studios", title: "A little maintenance. A better experience.", content: "We are planning maintenance to keep things running smoothly.\n\nDate and time: Add date, time and timezone\nExpected duration: Add duration\nAffected services: Add services\n\nWe will share an update when maintenance is complete. Thank you for your patience.", action: "Visit the studio", path: "/", badge: "SERVICE NOTICE", color: "#fde9ae" },
  { id: "alert", label: "Alert", description: "Important information for your community", subject: "Important notice — ZCraft Studios", title: "An important update for you.", content: "Please review this important update.\n\nWhat happened: Add the details\nWho is affected: Add affected services or customers\nWhat to do next: Add the recommended action\n\nNeed help? Reply to this email and our team will assist you.", action: "Visit the studio", path: "/", badge: "IMPORTANT NOTICE", color: "#edc4b1" },
  { id: "product", label: "Product launch", description: "Introduce your next server resource", subject: "Your next server upgrade is here", title: "Built for your next big idea.", content: "Meet our latest resource for your Minecraft server.\n\nAdd the product name, key features, compatibility and what makes it special.\n\nReady to build something great? Explore the collection below.", action: "Explore resources", path: "/products", badge: "NEW RESOURCE", color: "#b7e687" },
  { id: "sale", label: "Sale & offer", description: "Share discounts and limited offers", subject: "A studio offer, just for you", title: "More possibilities. A little less.", content: "Our latest offer is here.\n\nOffer: Add the discount or special deal\nValid until: Add the closing date, time and timezone\nHow to redeem: Add any required code or instructions\n\nAdd applicable conditions before sending.", action: "Shop resources", path: "/products", badge: "STUDIO OFFER", color: "#b7e687" },
] as const;
export type EmailTemplate = (typeof emailTemplates)[number];
export type TemplateFields = { title: string; content: string; action: string; url: string };
const escape = (value: string) => value.replace(/[&<>"']/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]!);
export function renderEmailTemplate(template: EmailTemplate, fields: TemplateFields): string {
  const url = new URL(fields.url);
  if (!["https:", "http:"].includes(url.protocol)) throw new Error("Use an HTTPS or HTTP button link.");
  const paragraphs = fields.content.split(/\n\s*\n/).map(p => `<p style="margin:0 0 20px;font-size:16px;line-height:1.75;color:#53606b">${escape(p).replace(/\n/g, "<br>")}</p>`).join("");
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f7f4ec;font-family:'Space Grotesk',Arial,sans-serif;color:#1c2028"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f7f4ec"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;border:1px solid #1c2028;border-radius:14px;background:#ffffff;overflow:hidden"><tr><td style="padding:28px 30px;background:#171b23;color:#f7f4ec;font-size:23px;font-weight:700;letter-spacing:-1px">ZCraft<span style="color:#73cec5"> Studios</span></td></tr><tr><td style="padding:18px 30px;background:${template.color};border-bottom:1px solid #1c2028;font-family:'JetBrains Mono','Courier New',monospace;font-size:11px;font-weight:700;letter-spacing:2px">${template.badge}</td></tr><tr><td style="padding:32px 30px"><h1 style="margin:0 0 24px;font-size:34px;line-height:1.15;letter-spacing:-1px;color:#1c2028">${escape(fields.title)}</h1>${paragraphs}<table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="background:#73cec5;border:1px solid #1c2028;border-radius:8px"><a href="${escape(url.toString())}" style="display:inline-block;padding:15px 22px;font-size:14px;font-weight:700;color:#171b23;text-decoration:none">${escape(fields.action)} &rarr;</a></td></tr></table></td></tr><tr><td style="padding:22px 30px;border-top:1px solid #e5e2da;background:#f7f4ec;font-family:'Courier New',monospace;font-size:11px;line-height:1.7;color:#53606b">ZCRAFT STUDIOS<br>Resources for your next great server.</td></tr></table></td></tr></table></body></html>`;
}
